### ISSUE TITLE
Content Issue #2: "Contact" Form Buttons Hidden

### ISSUE THREAD

**Issue by alishachawla14** [Muegalue/Project#10]
![Issue 5](https://user-images.githubusercontent.com/112462901/201375934-9e6c8609-c742-4dde-a27f-ff9c14584535.jpg)
![Issue 5b](https://user-images.githubusercontent.com/112462901/201375948-8021c900-4922-434d-bc34-d61526505ffd.jpg)

On the “Contact” page - the footer overlays the buttons so that the form cannot be submitted. This can be solved by removing the “margin: auto;” in the container and instead I recommend you add margin-bottom: 5em; in the container.

**Comment by Muegalue** [comment]
thank you for your responses.
