### ISSUE TITLE
Technical Issue #1: Variable Appearance

### ISSUE THREAD

**Issue by ronaldliujr** [Muegalue/Project#2]
https://github.com/Muegalue/Project/blob/0eb1f800cc3e5e4197dd1c2272cb7663d71fde8f/2-eat.html#L188

I noticed when looking through your code that you had this `<div class="left"></div>` in many of your files. There is no code in between the div tags, so I was confused what its purpose was. I noticed that you reference it in under the style section -> `.hero .left{
            background-image: url(images/eat-3.jpeg);
            background-size: cover;
            height: 60vh;
            background-repeat: no-repeat;
            background-position: center;`. However, since there is nothing in between the `<div>` tags, nothing is happening.

**Comment by Muegalue** [comment]
Noted! Thank you for letting me know.
