### ISSUE TITLE
Technical Issue #2: Variable Appearance

### ISSUE THREAD

**Issue by ronaldliujr** [Muegalue/Project#3]
https://github.com/Muegalue/Project/blob/0eb1f800cc3e5e4197dd1c2272cb7663d71fde8f/2-eat.html#L90

On many of your pages currently, there seems to be a bit of an appearance issue. Looking at your website from the Babson laptop, many of your content looks to be overlapping, covering parts of your navigation bar and actual content. I think this could be due to the percentages you use to set your content box and images. Instead of using percentages, using "px" measurements for all of those instead might fix this issue. Look at the screenshots below to see what I see from my end.

![image](https://user-images.githubusercontent.com/112499621/200716220-ce031954-6f32-4870-8d24-c437bb942ca7.png)
![image](https://user-images.githubusercontent.com/112499621/200716260-dc2d23d4-8b99-466d-984e-44e6b4ca86b0.png)

**Comment by Muegalue** [comment]
Thanks for leaving a screenshot, I'll work on it.
