### ISSUE TITLE
Content Issue #1: Span tag is not closed

### ISSUE THREAD

**Issue by ronaldliujr** [Muegalue/Project#4]
https://github.com/Muegalue/Project/blob/0eb1f800cc3e5e4197dd1c2272cb7663d71fde8f/2-eat.html#L216

I think this was a simple mistake, but in line 216 on your Eats page, you forgot to close the ending `<span>` tag. If you just add the < sign to the front of it, this will solve the issue.

![image](https://user-images.githubusercontent.com/112499621/200717321-1cea0ace-e9de-45ac-b02c-0f3f1b62a511.png)

**Comment by Muegalue** [comment]
Thanks Ronald!
