### ISSUE TITLE
Technical Issue #1: White Text Blocks

### ISSUE THREAD

**Issue by alishachawla14** [Muegalue/Project#6]
![Issue 1](https://user-images.githubusercontent.com/112462901/201372644-8571c5b7-5b30-4edd-bc01-83813cf2299e.jpg)
![issue 1b](https://user-images.githubusercontent.com/112462901/201372653-3aeb55a7-b559-4c72-b1ce-bda10e8cbdf2.jpg)

On the home page, there are white text blocks on a white background (“Explore Bangkok Through a Local Lens." From the code: <“div class = hero-content”> you can see that.

**Comment by Muegalue** [comment]
Yeah, it appear different while I was developing. I'll work on that, thank you.
