### ISSUE TITLE
Technical Issue #2: Stylesheets vs. Style Elements 

### ISSUE THREAD

**Issue by alishachawla14** [Muegalue/Project#7]
![Issue 2](https://user-images.githubusercontent.com/112462901/201373006-930cdd26-d71d-4143-92aa-60bf68ef747d.jpg)
From looking at your code, you need to have a separate Stylesheet vs. just a Style Element embedded within your pages.

**Comment by Muegalue** [comment]
I find it easier to do it on the same page, but I do understand what you mean. I will improve upon that. Thank you.
