### ISSUE TITLE
Technical Issue #3: Stylistic Issues on play.html Page

### ISSUE THREAD

**Issue by alishachawla14** [Muegalue/Project#8]
![Issue 3](https://user-images.githubusercontent.com/112462901/201375033-3f5261f5-e5a3-42f1-9604-2d454ac40a2d.jpg)
![Issue 3b](https://user-images.githubusercontent.com/112462901/201375063-e70f785b-3921-4ac3-b3f4-e5f0209b916b.jpg)
On the “Play” page, take out transform: translate (-20%, 50%), and you can actually see the text.

**Comment by Muegalue** [comment]
I think it is the sizing issue, again I'll fix on that thank you
